#pragma once

#include "CoreMinimal.h"


	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_HasZombieInSight;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_ClosestZombie;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_TargetLocation;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_TargetItem;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_TargetHouse;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_HasWeapon;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_ZombieIsFaster;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_HasCriticalHealth;
	extern DETOLLENAEREWANNESZOMBIERUNTIME_API const FName BBK_IsExecutingCombatRotation;
